#!/bin/sh

BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ "$BRANCH" = "main" ] || [ "$BRANCH" = "master" ]; then
  echo "❌ Direct push to '$BRANCH' is not allowed. Create a PR instead."
  exit 1
fi
